### ISSUE TITLE
Make `deploy.yml` action depend on `validate.yml` action

### ISSUE THREAD

**Issue by PeterKraus** [datatractor/yard#10]
Originally in https://github.com/marda-alliance/metadata_extractors_registry/issues/82. I believe this is still open, as there doesn't seem to be a dependency chain in the current GH actions.

**Comment by ml-evs** [comment]
We only merge if something is valid though, so think this is fine

**Comment by PeterKraus** [comment]
Yup, I think deployment on actual releases gives us this for free.
