### ISSUE TITLE
Deployed versions of `yard` are always dirty

### ISSUE THREAD

**Issue by PeterKraus** [datatractor/yard#14]
The currently deployed version corresponds to the `0.0.2` tag of this repo. When deployed locally, the api is available under the correct `/api/v0.0.2` path. However, when built with the dockerfile and deployed on https://yard.datatractor.org, the api version resolves to a dirty one:

![image](https://github.com/datatractor/yard/assets/5336995/18ff53b1-d066-4c77-b7f4-b7814c66233f)

My hunch is that either `app/` should be added to the `.gitignore`, or the mount-bind in the dockerfile somehow leaves the state dirty:

https://github.com/datatractor/yard/blob/d06056a406c5eb4cdd767991435f0b3b76fe25eb/Dockerfile#L18C1-L18C65

**Comment by ml-evs** [comment]
After playing around with this locally I think its unavoidable, the lfs data for e.g., is "dirty" after the build, plus many files are not copied in. I'll just disable the dirty versioning altogether, I don't think we need it.

**Comment by ml-evs** [comment]
Closed by 12f0be9
